/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import bean.ApmProduto;
import tools.Util;

/**
 *
 * @author win10
 */
public class JDlgApmProduto extends javax.swing.JDialog {

    /**
     * Creates new form JDlgProduto
     */
    public JDlgApmProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Produto");
        setLocationRelativeTo(null);
        Util.habilitar(false, jTxtApmId, jTxtApmNome, jTxtApmMarca,
                jTxtApmTamanho, jTxtApmPreco, jTxtApmTipo, jFmtApmDataValidade,
                jBtnApmConfirmar, jBtnApmCancelar);
        Util.limpar(jTxtApmId, jTxtApmNome, jTxtApmMarca,
                jTxtApmTamanho, jTxtApmPreco, jTxtApmTipo, jFmtApmDataValidade);
    }
    
    public void beanView(ApmProduto apmProduto){
        jTxtApmId.setText(Util.intToStr(apmProduto.getApmIdProduto()));
        jTxtApmNome.setText(apmProduto.getApmNome());
        jTxtApmMarca.setText(apmProduto.getApmMarca());
        jTxtApmTamanho.setText(apmProduto.getApmTamanho());
        jTxtApmPreco.setText(Util.doubleToStr(apmProduto.getApmValor()));
        jTxtApmTipo.setText(apmProduto.getApmTipo());
        jFmtApmDataValidade.setText(Util.dateToStr(apmProduto.getApmDataValidade()));     
    }
    
    public void viewBean(){
        ApmProduto apmProduto = new ApmProduto();
        int apmId = Util.strToInt((jTxtApmId.getText()));
        apmProduto.setApmNome(jTxtApmNome.getText());
        apmProduto.setApmMarca(jTxtApmMarca.getText());
        apmProduto.setApmTamanho(jTxtApmTamanho.getText());
        apmProduto.setApmValor(Util.strToDouble(jTxtApmPreco.getText()));
        apmProduto.setApmTipo(jTxtApmTipo.getText());
        apmProduto.setApmDataValidade(Util.strToDate(jFmtApmDataValidade.getText()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtApmMarca = new javax.swing.JTextField();
        jFmtApmDataValidade = new javax.swing.JFormattedTextField();
        jLblApmPreco = new javax.swing.JLabel();
        jLblApmId = new javax.swing.JLabel();
        jLblApmNome = new javax.swing.JLabel();
        jTxtApmPreco = new javax.swing.JTextField();
        jLblApmMarca = new javax.swing.JLabel();
        jLblApmTipo = new javax.swing.JLabel();
        jLblApmDataValidade = new javax.swing.JLabel();
        jLblApmTamanho = new javax.swing.JLabel();
        jTxtApmId = new javax.swing.JTextField();
        jTxtApmTipo = new javax.swing.JTextField();
        jTxtApmNome = new javax.swing.JTextField();
        jTxtApmTamanho = new javax.swing.JTextField();
        jBtnApmAlterar = new javax.swing.JButton();
        jBtnApmExcluir = new javax.swing.JButton();
        jBtnApmCancelar = new javax.swing.JButton();
        jBtnApmConfirmar = new javax.swing.JButton();
        jBtnApmPesquisar = new javax.swing.JButton();
        jBtnApmIncluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTxtApmMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtApmMarcaActionPerformed(evt);
            }
        });

        jLblApmPreco.setText("Preço");

        jLblApmId.setText("Id");

        jLblApmNome.setText("Nome");

        jLblApmMarca.setText("Marca");

        jLblApmTipo.setText("Tipo");

        jLblApmDataValidade.setText("Data de validade");

        jLblApmTamanho.setText("Tamanho");

        jTxtApmNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtApmNomeActionPerformed(evt);
            }
        });

        jBtnApmAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnApmAlterar.setText("Alterar");
        jBtnApmAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApmAlterarActionPerformed(evt);
            }
        });

        jBtnApmExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir_1.png"))); // NOI18N
        jBtnApmExcluir.setText("Excluir");
        jBtnApmExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApmExcluirActionPerformed(evt);
            }
        });

        jBtnApmCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnApmCancelar.setText("Cancelar");
        jBtnApmCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApmCancelarActionPerformed(evt);
            }
        });

        jBtnApmConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar.png"))); // NOI18N
        jBtnApmConfirmar.setText("Confirmar");
        jBtnApmConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApmConfirmarActionPerformed(evt);
            }
        });

        jBtnApmPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar_1.png"))); // NOI18N
        jBtnApmPesquisar.setText("Pesquisar");
        jBtnApmPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApmPesquisarActionPerformed(evt);
            }
        });

        jBtnApmIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok_1.png"))); // NOI18N
        jBtnApmIncluir.setText("Incluir");
        jBtnApmIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApmIncluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtApmMarca)
                    .addComponent(jTxtApmNome)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jFmtApmDataValidade)
                                    .addComponent(jLblApmId)
                                    .addComponent(jLblApmNome)
                                    .addComponent(jLblApmMarca)
                                    .addComponent(jTxtApmId, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLblApmDataValidade)
                                    .addComponent(jLblApmTipo)
                                    .addComponent(jTxtApmTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLblApmTamanho)
                                    .addComponent(jLblApmPreco)
                                    .addComponent(jTxtApmPreco)
                                    .addComponent(jTxtApmTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnApmIncluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnApmAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnApmExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnApmCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnApmConfirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnApmPesquisar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblApmId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtApmId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLblApmNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtApmNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLblApmMarca)
                .addGap(4, 4, 4)
                .addComponent(jTxtApmMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblApmDataValidade)
                    .addComponent(jLblApmPreco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtApmDataValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtApmPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblApmTipo)
                    .addComponent(jLblApmTamanho))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtApmTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtApmTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnApmIncluir)
                    .addComponent(jBtnApmAlterar)
                    .addComponent(jBtnApmExcluir)
                    .addComponent(jBtnApmCancelar)
                    .addComponent(jBtnApmConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnApmPesquisar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtApmMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtApmMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtApmMarcaActionPerformed

    private void jTxtApmNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtApmNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtApmNomeActionPerformed

    private void jBtnApmIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApmIncluirActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jTxtApmId, jTxtApmNome, jTxtApmMarca,
                jTxtApmTamanho, jTxtApmPreco, jTxtApmTipo, jFmtApmDataValidade,
                jBtnApmConfirmar, jBtnApmCancelar);
        Util.habilitar(false, jBtnApmIncluir, jBtnApmAlterar, jBtnApmExcluir, jBtnApmPesquisar);
        Util.limpar(jTxtApmId, jTxtApmNome, jTxtApmMarca,
                jTxtApmTamanho, jTxtApmPreco, jTxtApmTipo, jFmtApmDataValidade);
    }//GEN-LAST:event_jBtnApmIncluirActionPerformed

    private void jBtnApmAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApmAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnApmAlterarActionPerformed

    private void jBtnApmExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApmExcluirActionPerformed
        // TODO add your handling code here:
        Util.pergunta("Deseja mesmo excluir?");
    }//GEN-LAST:event_jBtnApmExcluirActionPerformed

    private void jBtnApmCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApmCancelarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jTxtApmId, jTxtApmNome, jTxtApmMarca,
                jTxtApmTamanho, jTxtApmPreco, jTxtApmTipo, jFmtApmDataValidade,
                jBtnApmConfirmar, jBtnApmCancelar);
        Util.habilitar(true, jBtnApmIncluir, jBtnApmAlterar, jBtnApmExcluir, jBtnApmPesquisar);
  
    }//GEN-LAST:event_jBtnApmCancelarActionPerformed

    private void jBtnApmConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApmConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnApmConfirmarActionPerformed

    private void jBtnApmPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApmPesquisarActionPerformed
        // TODO add your handling code here:
        JDlgApmProdutoPesquisar jDlgApmProdutoPesquisar = new JDlgApmProdutoPesquisar(null, true);
        jDlgApmProdutoPesquisar.setVisible(true);
    }//GEN-LAST:event_jBtnApmPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgApmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgApmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgApmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgApmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgApmProduto dialog = new JDlgApmProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnApmAlterar;
    private javax.swing.JButton jBtnApmCancelar;
    private javax.swing.JButton jBtnApmConfirmar;
    private javax.swing.JButton jBtnApmExcluir;
    private javax.swing.JButton jBtnApmIncluir;
    private javax.swing.JButton jBtnApmPesquisar;
    private javax.swing.JFormattedTextField jFmtApmDataValidade;
    private javax.swing.JLabel jLblApmDataValidade;
    private javax.swing.JLabel jLblApmId;
    private javax.swing.JLabel jLblApmMarca;
    private javax.swing.JLabel jLblApmNome;
    private javax.swing.JLabel jLblApmPreco;
    private javax.swing.JLabel jLblApmTamanho;
    private javax.swing.JLabel jLblApmTipo;
    private javax.swing.JTextField jTxtApmId;
    private javax.swing.JTextField jTxtApmMarca;
    private javax.swing.JTextField jTxtApmNome;
    private javax.swing.JTextField jTxtApmPreco;
    private javax.swing.JTextField jTxtApmTamanho;
    private javax.swing.JTextField jTxtApmTipo;
    // End of variables declaration//GEN-END:variables
}
