/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import bean.ApmFuncionario;
import tools.Util;

/**
 *
 * @author win10
 */
public class JDlgApmFuncionario extends javax.swing.JDialog {

    /**
     * Creates new form JDlgFuncionario
     */
    public JDlgApmFuncionario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Funcionario");
        setLocationRelativeTo(null);
        Util.habilitar(false, jTxtApmId, jTxtApmNome, jTxtApmApelido,
                jFmtApmCpf, jFmtApmDataNascimento, jCboApmNivel, 
                jChbApmAtivo, jPwfApmSenha, jBtnApmConfirmar, jBtnApmCancelar);
        Util.limpar(jTxtApmId, jTxtApmNome, jTxtApmApelido, 
                jFmtApmCpf, jFmtApmDataNascimento, jCboApmNivel, 
                jChbApmAtivo, jPwfApmSenha);
    }   
    
    public void beanView(ApmFuncionario apmFuncionario){
        jTxtApmId.setText(Util.intToStr(apmFuncionario.getApmIdFuncionario()));
        jTxtApmNome.setText(apmFuncionario.getApmNome());
        jTxtApmApelido.setText(apmFuncionario.getApmApelido());
        jFmtApmCpf.setText(apmFuncionario.getApmCpf());
        jFmtApmDataNascimento.setText(Util.dateToStr(apmFuncionario.getApmDataNascimento()));
        jCboApmNivel.setSelectedIndex(apmFuncionario.getApmNivel());
        jPwfApmSenha.setText(apmFuncionario.getApmSenha());
        if( apmFuncionario.getApmAtivo().equals("S") == true){
            jChbApmAtivo.setSelected(true);
        } else {
            jChbApmAtivo.setSelected(false);
        }
    }
    
    public ApmFuncionario viewBean(){
        ApmFuncionario apmFuncionario = new ApmFuncionario();
        int apmId = Util.strToInt(jTxtApmId.getText());
        apmFuncionario.setApmNome(jTxtApmNome.getText());
        apmFuncionario.setApmApelido(jTxtApmApelido.getText());
        apmFuncionario.setApmCpf(jFmtApmCpf.getText());
        apmFuncionario.setApmDataNascimento(Util.strToDate(jFmtApmDataNascimento.getText()));
        apmFuncionario.setApmNivel(jCboApmNivel.getSelectedIndex());
        apmFuncionario.setApmSenha(jPwfApmSenha.getText());
        if (jChbApmAtivo.isSelected() == true){
            apmFuncionario.setApmAtivo("S");
        } else {
            apmFuncionario.setApmAtivo("N");
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblApmNome = new javax.swing.JLabel();
        jChbApmAtivo = new javax.swing.JCheckBox();
        jFmtApmDataNascimento = new javax.swing.JFormattedTextField();
        jCboApmNivel = new javax.swing.JComboBox<String>();
        jLblApmCpf = new javax.swing.JLabel();
        jLblApmApelido = new javax.swing.JLabel();
        jFmtApmCpf = new javax.swing.JFormattedTextField();
        jTxtApmId = new javax.swing.JTextField();
        jPwfApmSenha = new javax.swing.JPasswordField();
        jTxtApmNome = new javax.swing.JTextField();
        jLblApmSenha = new javax.swing.JLabel();
        jTxtApmApelido = new javax.swing.JTextField();
        jLblApmNivel = new javax.swing.JLabel();
        jLbApmlId = new javax.swing.JLabel();
        jLbApmlAtivo = new javax.swing.JLabel();
        jLblApmDataNascimento = new javax.swing.JLabel();
        jBtnApmAlterar = new javax.swing.JButton();
        jBtnApmExcluir = new javax.swing.JButton();
        jBtnApmCancelar = new javax.swing.JButton();
        jBtnApmConfirmar = new javax.swing.JButton();
        jBtnApmPesquisar = new javax.swing.JButton();
        jBtnApmIncluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblApmNome.setText("Nome");

        jCboApmNivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Caixa", "Vendedor", "Repositor", " " }));

        jLblApmCpf.setText("Cpf");

        jLblApmApelido.setText("Apelido");

        jTxtApmNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtApmNomeActionPerformed(evt);
            }
        });

        jLblApmSenha.setText("Senha");

        jTxtApmApelido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtApmApelidoActionPerformed(evt);
            }
        });

        jLblApmNivel.setText("Nível");

        jLbApmlId.setText("Id");

        jLbApmlAtivo.setText("Ativo");

        jLblApmDataNascimento.setText("Data De Nascimento");

        jBtnApmAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnApmAlterar.setText("Alterar");
        jBtnApmAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApmAlterarActionPerformed(evt);
            }
        });

        jBtnApmExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir_1.png"))); // NOI18N
        jBtnApmExcluir.setText("Excluir");
        jBtnApmExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApmExcluirActionPerformed(evt);
            }
        });

        jBtnApmCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar_1.png"))); // NOI18N
        jBtnApmCancelar.setText("Cancelar");
        jBtnApmCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApmCancelarActionPerformed(evt);
            }
        });

        jBtnApmConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar.png"))); // NOI18N
        jBtnApmConfirmar.setText("Confirmar");
        jBtnApmConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApmConfirmarActionPerformed(evt);
            }
        });

        jBtnApmPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnApmPesquisar.setText("Pesquisar");
        jBtnApmPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApmPesquisarActionPerformed(evt);
            }
        });

        jBtnApmIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok_1.png"))); // NOI18N
        jBtnApmIncluir.setText("Incluir");
        jBtnApmIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApmIncluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtApmNome)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtApmApelido)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblApmApelido)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLblApmDataNascimento)
                                            .addComponent(jFmtApmDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLblApmSenha)
                                            .addComponent(jPwfApmSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblApmNivel)
                            .addComponent(jCboApmNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jChbApmAtivo)
                            .addComponent(jLbApmlAtivo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblApmNome)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtApmId, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(jFmtApmCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLbApmlId)
                                .addGap(250, 250, 250)
                                .addComponent(jLblApmCpf)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnApmIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnApmAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnApmExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnApmCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnApmConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnApmPesquisar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbApmlId)
                    .addComponent(jLblApmCpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtApmId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtApmCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLblApmNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtApmNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblApmNivel)
                        .addGap(4, 4, 4)
                        .addComponent(jCboApmNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLbApmlAtivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jChbApmAtivo))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLblApmSenha)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPwfApmSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLblApmApelido)
                            .addGap(4, 4, 4)
                            .addComponent(jTxtApmApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLblApmDataNascimento)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jFmtApmDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnApmIncluir)
                    .addComponent(jBtnApmAlterar)
                    .addComponent(jBtnApmExcluir)
                    .addComponent(jBtnApmCancelar)
                    .addComponent(jBtnApmConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnApmPesquisar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtApmNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtApmNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtApmNomeActionPerformed

    private void jTxtApmApelidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtApmApelidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtApmApelidoActionPerformed

    private void jBtnApmIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApmIncluirActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jTxtApmId, jTxtApmNome, jTxtApmApelido,
                jFmtApmCpf, jFmtApmDataNascimento, jCboApmNivel, 
                jChbApmAtivo, jPwfApmSenha, jBtnApmConfirmar, jBtnApmCancelar);
        Util.habilitar(false, jBtnApmIncluir, jBtnApmAlterar, jBtnApmExcluir, jBtnApmPesquisar);
        Util.limpar(jTxtApmId, jTxtApmNome, jTxtApmApelido, 
                jFmtApmCpf, jFmtApmDataNascimento, jCboApmNivel, 
                jChbApmAtivo, jPwfApmSenha);
    }//GEN-LAST:event_jBtnApmIncluirActionPerformed

    private void jBtnApmAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApmAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnApmAlterarActionPerformed

    private void jBtnApmExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApmExcluirActionPerformed
        // TODO add your handling code here:
        Util.pergunta("Deseja mesmo excluir?");
    }//GEN-LAST:event_jBtnApmExcluirActionPerformed

    private void jBtnApmCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApmCancelarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jTxtApmId, jTxtApmNome, jTxtApmApelido,
                jFmtApmCpf, jFmtApmDataNascimento, jCboApmNivel, 
                jChbApmAtivo, jPwfApmSenha, jBtnApmConfirmar, jBtnApmCancelar);
        Util.habilitar(true, jBtnApmIncluir, jBtnApmAlterar, jBtnApmExcluir, jBtnApmPesquisar);
    }//GEN-LAST:event_jBtnApmCancelarActionPerformed

    private void jBtnApmConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApmConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnApmConfirmarActionPerformed

    private void jBtnApmPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApmPesquisarActionPerformed
        // TODO add your handling code here:   
        JDlgApmFuncionarioPesquisar jDlgApmFuncionarioPesquisar =  new JDlgApmFuncionarioPesquisar(null, true);
        jDlgApmFuncionarioPesquisar.setVisible(true);
    }//GEN-LAST:event_jBtnApmPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgApmFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgApmFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgApmFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgApmFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgApmFuncionario dialog = new JDlgApmFuncionario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnApmAlterar;
    private javax.swing.JButton jBtnApmCancelar;
    private javax.swing.JButton jBtnApmConfirmar;
    private javax.swing.JButton jBtnApmExcluir;
    private javax.swing.JButton jBtnApmIncluir;
    private javax.swing.JButton jBtnApmPesquisar;
    private javax.swing.JComboBox<String> jCboApmNivel;
    private javax.swing.JCheckBox jChbApmAtivo;
    private javax.swing.JFormattedTextField jFmtApmCpf;
    private javax.swing.JFormattedTextField jFmtApmDataNascimento;
    private javax.swing.JLabel jLbApmlAtivo;
    private javax.swing.JLabel jLbApmlId;
    private javax.swing.JLabel jLblApmApelido;
    private javax.swing.JLabel jLblApmCpf;
    private javax.swing.JLabel jLblApmDataNascimento;
    private javax.swing.JLabel jLblApmNivel;
    private javax.swing.JLabel jLblApmNome;
    private javax.swing.JLabel jLblApmSenha;
    private javax.swing.JPasswordField jPwfApmSenha;
    private javax.swing.JTextField jTxtApmApelido;
    private javax.swing.JTextField jTxtApmId;
    private javax.swing.JTextField jTxtApmNome;
    // End of variables declaration//GEN-END:variables
}
