/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import bean.ApmCliente;
import tools.Util;

/**
 *
 * @author win10
 */
public class JDlgApmCliente extends javax.swing.JDialog {

    /**
     * Creates new form JDlgCliente
     */
    public JDlgApmCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("cadastro de Cliente");
        setLocationRelativeTo(null);
        Util.habilitar(false, jTxtApmId, jTxtApmNome, jTxtApmApelido,
                jTxtApmEmail, jPwsSenha, jTxtApmCelular, jTxtApmTelefone, jTxtCep,
                jTxtApmBairro, jTxtApmRua, jFmtApmCpf,
                jFmtApmDataNascimento, jFmtApmRg, jCboApmSexo, jChbApmAtivo,
                jBtnApmConfirmar, jBtnApmCancelar);
        Util.limpar(jTxtApmId, jTxtApmNome, jTxtApmApelido,
                jTxtApmEmail, jPwsSenha, jTxtApmCelular, jTxtApmTelefone, jTxtCep,
                jTxtApmBairro, jTxtApmRua, jFmtApmCpf,
                jFmtApmDataNascimento, jFmtApmRg, jCboApmSexo, jChbApmAtivo);
    }
    
    public void beanView(ApmCliente apmCliente){
        jTxtApmId.setText(Util.intToStr(apmCliente.getApmIdCliente()));
        jTxtApmNome.setText(apmCliente.getApmNome());
        jTxtApmApelido.setText(apmCliente.getApmApelido());
        jTxtApmEmail.setText(apmCliente.getApmEmail());
        jPwsSenha.setText(apmCliente.getApmSenha());
        jTxtApmCelular.setText(apmCliente.getApmCelular());
        jTxtApmTelefone.setText(apmCliente.getApmTelefone());
        jTxtCep.setText(apmCliente.getApmCep());
        jTxtApmBairro.setText(apmCliente.getApmBairro());
        jTxtApmRua.setText(apmCliente.getApmRua());;
        jFmtApmCpf.setText((apmCliente.getApmCpf()));
        jFmtApmDataNascimento.setText(Util.dateToStr(apmCliente.getApmDataNascimento()));
        jFmtApmRg.setText(apmCliente.getApmRg());
        jCboApmSexo.setSelectedIndex(apmCliente.getApmSexo());
        if( apmCliente.getApmAtivo().equals("S") == true){
            jChbApmAtivo.setSelected(true);
        } else {
            jChbApmAtivo.setSelected(false);
        }
    }
    
    public ApmCliente viewBean(){
        ApmCliente apmCliente = new ApmCliente();
        int apmId = Util.strToInt(jTxtApmId.getText());
        apmCliente.setApmNome(jTxtApmNome.getText());
        apmCliente.setApmApelido(jTxtApmApelido.getText());
        apmCliente.setApmEmail(jTxtApmEmail.getText());
        apmCliente.setApmSenha(jPwsSenha.getText());
        apmCliente.setApmCelular(jTxtApmCelular.getText());
        apmCliente.setApmTelefone(jTxtApmTelefone.getText());
        apmCliente.setApmCep(jTxtCep.getText());
        apmCliente.setApmBairro(jTxtApmBairro.getText());
        apmCliente.setApmRua(jTxtApmRua.getText());
        apmCliente.setApmCpf(jFmtApmCpf.getText());
        apmCliente.setApmDataNascimento(Util.strToDate(jFmtApmDataNascimento.getText()));
        apmCliente.setApmRg(jFmtApmRg.getText());
        apmCliente.setApmSexo((char) jCboApmSexo.getSelectedIndex());
        if (jChbApmAtivo.isSelected() == true){
            apmCliente.setApmAtivo("S");
        } else {
            apmCliente.setApmAtivo("N");
        }
        return null;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnApmConfirmar = new javax.swing.JButton();
        jTxtApmId = new javax.swing.JTextField();
        jTxtApmEmail = new javax.swing.JTextField();
        jBtnApmExcluir = new javax.swing.JButton();
        jLblApmTelefone = new javax.swing.JLabel();
        jTxtApmTelefone = new javax.swing.JTextField();
        jBtnApmCancelar = new javax.swing.JButton();
        jTxtApmNome = new javax.swing.JTextField();
        jLblApmCelular = new javax.swing.JLabel();
        jLbApmlId = new javax.swing.JLabel();
        jTxtApmCelular = new javax.swing.JTextField();
        jLblApmNome = new javax.swing.JLabel();
        jLblApmApelido = new javax.swing.JLabel();
        jLblApmRua = new javax.swing.JLabel();
        jTxtApmApelido = new javax.swing.JTextField();
        jFmtApmDataNascimento = new javax.swing.JFormattedTextField();
        jLblApmCpf = new javax.swing.JLabel();
        jLblApmBairro = new javax.swing.JLabel();
        jLblApmRg = new javax.swing.JLabel();
        jLblApmCep = new javax.swing.JLabel();
        jFmtApmCpf = new javax.swing.JFormattedTextField();
        jLblApmSexo = new javax.swing.JLabel();
        jFmtApmRg = new javax.swing.JFormattedTextField();
        jLblApmAtivo = new javax.swing.JLabel();
        jCboApmSexo = new javax.swing.JComboBox<String>();
        jTxtApmRua = new javax.swing.JTextField();
        jTxtApmBairro = new javax.swing.JTextField();
        jTxtCep = new javax.swing.JTextField();
        jBtnApmPesquisar = new javax.swing.JButton();
        jBtnApmIncluir = new javax.swing.JButton();
        jLblApmDataNascimento = new javax.swing.JLabel();
        jChbApmAtivo = new javax.swing.JCheckBox();
        jLblApmEmail = new javax.swing.JLabel();
        jBtnApmAlterar = new javax.swing.JButton();
        jLblSenha = new javax.swing.JLabel();
        jPwsSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtnApmConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar.png"))); // NOI18N
        jBtnApmConfirmar.setText("Confirmar");
        jBtnApmConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApmConfirmarActionPerformed(evt);
            }
        });

        jTxtApmEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtApmEmailActionPerformed(evt);
            }
        });

        jBtnApmExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnApmExcluir.setText("Excluir");
        jBtnApmExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApmExcluirActionPerformed(evt);
            }
        });

        jLblApmTelefone.setText("Telefone");

        jBtnApmCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar_1.png"))); // NOI18N
        jBtnApmCancelar.setText("Cancelar");
        jBtnApmCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApmCancelarActionPerformed(evt);
            }
        });

        jTxtApmNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtApmNomeActionPerformed(evt);
            }
        });

        jLblApmCelular.setText("Celular");

        jLbApmlId.setText("Id");

        jLblApmNome.setText("Nome");

        jLblApmApelido.setText("Apelido");

        jLblApmRua.setText("Rua");

        jTxtApmApelido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtApmApelidoActionPerformed(evt);
            }
        });

        jLblApmCpf.setText("Cpf");

        jLblApmBairro.setText("Bairro");

        jLblApmRg.setText("Rg");

        jLblApmCep.setText("CEP");

        jLblApmSexo.setText("Sexo");

        jLblApmAtivo.setText("Ativo");

        jCboApmSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Feminino", "Masculino", " " }));

        jTxtApmRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtApmRuaActionPerformed(evt);
            }
        });

        jBtnApmPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar_1.png"))); // NOI18N
        jBtnApmPesquisar.setText("Pesquisar");
        jBtnApmPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApmPesquisarActionPerformed(evt);
            }
        });

        jBtnApmIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnApmIncluir.setText("Incluir");
        jBtnApmIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApmIncluirActionPerformed(evt);
            }
        });

        jLblApmDataNascimento.setText("Data De Nascimento");

        jLblApmEmail.setText("Email");

        jBtnApmAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnApmAlterar.setText("Alterar");
        jBtnApmAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApmAlterarActionPerformed(evt);
            }
        });

        jLblSenha.setText("Senha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtApmNome)
                    .addComponent(jTxtCep)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtApmApelido)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLblApmApelido)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTxtApmEmail)
                                        .addGap(253, 253, 253)))
                                .addGap(19, 19, 19))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPwsSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLblApmEmail)
                                                .addGap(270, 270, 270)
                                                .addComponent(jLblSenha))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLblApmDataNascimento)
                                                    .addComponent(jFmtApmDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jFmtApmCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLblApmCpf))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLblApmRg)
                                            .addComponent(jFmtApmRg, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCboApmSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblApmSexo)
                            .addComponent(jChbApmAtivo)
                            .addComponent(jLblApmAtivo))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbApmlId)
                            .addComponent(jLblApmNome)
                            .addComponent(jTxtApmId, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblApmCep)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnApmIncluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnApmAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnApmExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnApmCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnApmConfirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnApmPesquisar)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblApmTelefone)
                            .addComponent(jTxtApmTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblApmCelular)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtApmCelular)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblApmRua)
                            .addComponent(jTxtApmRua, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtApmBairro)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblApmBairro)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLbApmlId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtApmId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLblApmNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblApmCpf)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtApmNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblApmApelido)
                                .addGap(4, 4, 4)
                                .addComponent(jTxtApmApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblApmSexo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCboApmSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLblApmAtivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jChbApmAtivo)
                                .addGap(5, 5, 5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLblApmDataNascimento)
                                    .addComponent(jLblApmRg))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFmtApmDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFmtApmCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFmtApmRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblApmEmail)
                    .addComponent(jLblSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtApmEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPwsSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblApmTelefone)
                    .addComponent(jLblApmCelular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtApmTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtApmCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblApmRua)
                    .addComponent(jLblApmBairro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtApmRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtApmBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLblApmCep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnApmIncluir)
                    .addComponent(jBtnApmAlterar)
                    .addComponent(jBtnApmExcluir)
                    .addComponent(jBtnApmCancelar)
                    .addComponent(jBtnApmConfirmar)
                    .addComponent(jBtnApmPesquisar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnApmConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApmConfirmarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jTxtApmId, jTxtApmNome, jTxtApmApelido,
                jTxtApmEmail, jPwsSenha, jTxtApmCelular, jTxtApmTelefone, jTxtCep,
                jTxtApmBairro, jTxtApmRua, jFmtApmCpf,
                jFmtApmDataNascimento, jFmtApmRg, jCboApmSexo, jChbApmAtivo,
                jBtnApmConfirmar, jBtnApmCancelar);
        Util.habilitar(true, jBtnApmIncluir, jBtnApmAlterar, jBtnApmExcluir, jBtnApmPesquisar);
        Util.limpar(jTxtApmId, jTxtApmNome, jTxtApmApelido,
                jTxtApmEmail, jPwsSenha, jTxtApmCelular, jTxtApmTelefone, jTxtCep,
                jTxtApmBairro, jTxtApmRua, jFmtApmCpf,
                jFmtApmDataNascimento, jFmtApmRg, jCboApmSexo, jChbApmAtivo);
    }//GEN-LAST:event_jBtnApmConfirmarActionPerformed

    private void jTxtApmEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtApmEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtApmEmailActionPerformed

    private void jBtnApmExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApmExcluirActionPerformed
        // TODO add your handling code here:
        Util.pergunta("Deseja mesmo excluir?");
    }//GEN-LAST:event_jBtnApmExcluirActionPerformed

    private void jBtnApmCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApmCancelarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jTxtApmId, jTxtApmNome, jTxtApmApelido,
                jTxtApmEmail, jPwsSenha, jTxtApmCelular, jTxtApmTelefone, jTxtCep,
                jTxtApmBairro, jTxtApmRua, jFmtApmCpf,
                jFmtApmDataNascimento, jFmtApmRg, jCboApmSexo, jChbApmAtivo,
                jBtnApmConfirmar, jBtnApmCancelar);
        Util.habilitar(true, jBtnApmIncluir, jBtnApmAlterar, jBtnApmExcluir, jBtnApmPesquisar);
    }//GEN-LAST:event_jBtnApmCancelarActionPerformed

    private void jTxtApmNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtApmNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtApmNomeActionPerformed

    private void jTxtApmApelidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtApmApelidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtApmApelidoActionPerformed

    private void jTxtApmRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtApmRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtApmRuaActionPerformed

    private void jBtnApmPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApmPesquisarActionPerformed
        // TODO add your handling code here:jTxtId.setEnabled(true);
        JDlgApmClientePesquisar jDlgApmClientePesquisar = new JDlgApmClientePesquisar(null, true);
        jDlgApmClientePesquisar.setVisible(true);
    }//GEN-LAST:event_jBtnApmPesquisarActionPerformed

    private void jBtnApmIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApmIncluirActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jTxtApmId, jTxtApmNome, jTxtApmApelido,
                jTxtApmEmail, jPwsSenha, jTxtApmCelular, jTxtApmTelefone, jTxtCep,
                jTxtApmBairro, jTxtApmRua, jFmtApmCpf,
                jFmtApmDataNascimento, jFmtApmRg, jCboApmSexo, jChbApmAtivo,
                jBtnApmConfirmar, jBtnApmCancelar);
        Util.habilitar(false, jBtnApmIncluir, jBtnApmAlterar, jBtnApmExcluir, jBtnApmPesquisar);
        Util.limpar(jTxtApmId, jTxtApmNome, jTxtApmApelido,
                jTxtApmEmail, jPwsSenha, jTxtApmCelular, jTxtApmTelefone, jTxtCep,
                jTxtApmBairro, jTxtApmRua, jFmtApmCpf,
                jFmtApmDataNascimento, jFmtApmRg, jCboApmSexo, jChbApmAtivo);
    }//GEN-LAST:event_jBtnApmIncluirActionPerformed

    private void jBtnApmAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApmAlterarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jTxtApmId, jTxtApmNome, jTxtApmApelido,
                jTxtApmEmail, jPwsSenha, jTxtApmCelular, jTxtApmTelefone, jTxtCep,
                jTxtApmBairro, jTxtApmRua, jFmtApmCpf,
                jFmtApmDataNascimento, jFmtApmRg, jCboApmSexo, jChbApmAtivo,
                jBtnApmConfirmar, jBtnApmCancelar);
        Util.habilitar(false, jBtnApmIncluir, jBtnApmAlterar, jBtnApmExcluir, jBtnApmPesquisar);
    }//GEN-LAST:event_jBtnApmAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgApmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgApmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgApmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgApmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgApmCliente dialog = new JDlgApmCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnApmAlterar;
    private javax.swing.JButton jBtnApmCancelar;
    private javax.swing.JButton jBtnApmConfirmar;
    private javax.swing.JButton jBtnApmExcluir;
    private javax.swing.JButton jBtnApmIncluir;
    private javax.swing.JButton jBtnApmPesquisar;
    private javax.swing.JComboBox<String> jCboApmSexo;
    private javax.swing.JCheckBox jChbApmAtivo;
    private javax.swing.JFormattedTextField jFmtApmCpf;
    private javax.swing.JFormattedTextField jFmtApmDataNascimento;
    private javax.swing.JFormattedTextField jFmtApmRg;
    private javax.swing.JLabel jLbApmlId;
    private javax.swing.JLabel jLblApmApelido;
    private javax.swing.JLabel jLblApmAtivo;
    private javax.swing.JLabel jLblApmBairro;
    private javax.swing.JLabel jLblApmCelular;
    private javax.swing.JLabel jLblApmCep;
    private javax.swing.JLabel jLblApmCpf;
    private javax.swing.JLabel jLblApmDataNascimento;
    private javax.swing.JLabel jLblApmEmail;
    private javax.swing.JLabel jLblApmNome;
    private javax.swing.JLabel jLblApmRg;
    private javax.swing.JLabel jLblApmRua;
    private javax.swing.JLabel jLblApmSexo;
    private javax.swing.JLabel jLblApmTelefone;
    private javax.swing.JLabel jLblSenha;
    private javax.swing.JPasswordField jPwsSenha;
    private javax.swing.JTextField jTxtApmApelido;
    private javax.swing.JTextField jTxtApmBairro;
    private javax.swing.JTextField jTxtApmCelular;
    private javax.swing.JTextField jTxtApmEmail;
    private javax.swing.JTextField jTxtApmId;
    private javax.swing.JTextField jTxtApmNome;
    private javax.swing.JTextField jTxtApmRua;
    private javax.swing.JTextField jTxtApmTelefone;
    private javax.swing.JTextField jTxtCep;
    // End of variables declaration//GEN-END:variables
}
