/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import bean.ApmUsuarios;
import bean.ApmUsuarios;
import tools.Util;

/**
 *
 * @author win10
 */
public class JDlgApmUsuario extends javax.swing.JDialog {

    /**
     * Creates new form Usuario
     */
    public JDlgApmUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Usuario");
        setLocationRelativeTo(null);
        Util.habilitar(false, jTxtApmId, jTxtApmNome, jTxtApmApelido, 
                                jFmtApmCpf, jFmtApmDataNasc, jPswApmSenha,
                            jCboApmNivel, jChbApmAtivo, jBtnApmConfirmar, jBtnApmCancelar);
        Util.limpar(jTxtApmId, jTxtApmNome, jTxtApmApelido, 
                                jFmtApmCpf, jFmtApmDataNasc, jPswApmSenha,
                            jCboApmNivel, jChbApmAtivo);
    }
 
    public void beanView(ApmUsuarios apmUsuarios){
        jTxtApmId.setText(Util.intToStr(apmUsuarios.getApmIdUsuario()));
        jTxtApmNome.setText(apmUsuarios.getApmNome());
        jTxtApmApelido.setText(apmUsuarios.getApmApelido());
        jFmtApmCpf.setText(apmUsuarios.getApmCpf());
        jFmtApmDataNasc.setText(Util.dateToStr(apmUsuarios.getApmDataNascimento()));
        jCboApmNivel.setSelectedIndex(apmUsuarios.getApmNivel());
        jPswApmSenha.setText(apmUsuarios.getApmSenha());
        if( apmUsuarios.getApmAtivo().equals("S") == true){
            jChbApmAtivo.setSelected(true);
        } else {
            jChbApmAtivo.setSelected(false);
        }
    }
    
    public ApmUsuarios viewBean(){
        ApmUsuarios apmUsuarios = new ApmUsuarios();
        int apmId = Util.strToInt(jTxtApmId.getText());
        apmUsuarios.setApmNome(jTxtApmNome.getText());
        apmUsuarios.setApmApelido(jTxtApmApelido.getText());
        apmUsuarios.setApmCpf(jFmtApmCpf.getText());
        apmUsuarios.setApmDataNascimento(Util.strToDate(jFmtApmDataNasc.getText()));
        apmUsuarios.setApmNivel(jCboApmNivel.getSelectedIndex());
        apmUsuarios.setApmSenha(jPswApmSenha.getText());
        if (jChbApmAtivo.isSelected() == true){
            apmUsuarios.setApmAtivo("S");
        } else {
            apmUsuarios.setApmAtivo("N");
        }
        return null;
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jLblApmId = new javax.swing.JLabel();
        jTxtApmId = new javax.swing.JTextField();
        jLblApmNome = new javax.swing.JLabel();
        jTxtApmNome = new javax.swing.JTextField();
        jLblApmApelido = new javax.swing.JLabel();
        jTxtApmApelido = new javax.swing.JTextField();
        jLblApmCpf = new javax.swing.JLabel();
        jFmtApmCpf = new javax.swing.JFormattedTextField();
        jLblApmSenha = new javax.swing.JLabel();
        jPswApmSenha = new javax.swing.JPasswordField();
        jChbApmAtivo = new javax.swing.JCheckBox();
        jLblApmNivel = new javax.swing.JLabel();
        jCboApmNivel = new javax.swing.JComboBox();
        jBtnApmIncluir = new javax.swing.JButton();
        jBtnApmAlterar = new javax.swing.JButton();
        jBtnApmExcluir = new javax.swing.JButton();
        jBtnApmCancelar = new javax.swing.JButton();
        jBtnApmConfirmar = new javax.swing.JButton();
        jBtnApmPesquisar = new javax.swing.JButton();
        jLblApmDataNascimento = new javax.swing.JLabel();
        jFmtApmDataNasc = new javax.swing.JFormattedTextField();

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblApmId.setText("ID");

        jLblApmNome.setText("Nome");

        jLblApmApelido.setText("Apelido");

        jLblApmCpf.setText("CPF");

        jLblApmSenha.setText("Senha");

        jPswApmSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPswApmSenhaActionPerformed(evt);
            }
        });

        jChbApmAtivo.setText("Ativo");

        jLblApmNivel.setText("Nível");

        jCboApmNivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jBtnApmIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok_1.png"))); // NOI18N
        jBtnApmIncluir.setText("Incluir");
        jBtnApmIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApmIncluirActionPerformed(evt);
            }
        });

        jBtnApmAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar_1.png"))); // NOI18N
        jBtnApmAlterar.setText("Alterar");
        jBtnApmAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApmAlterarActionPerformed(evt);
            }
        });

        jBtnApmExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir_1.png"))); // NOI18N
        jBtnApmExcluir.setText("Excluir");
        jBtnApmExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApmExcluirActionPerformed(evt);
            }
        });

        jBtnApmCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar_1.png"))); // NOI18N
        jBtnApmCancelar.setText("Cancelar");
        jBtnApmCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApmCancelarActionPerformed(evt);
            }
        });

        jBtnApmConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar.png"))); // NOI18N
        jBtnApmConfirmar.setText("Confirmar");
        jBtnApmConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApmConfirmarActionPerformed(evt);
            }
        });

        jBtnApmPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar_1.png"))); // NOI18N
        jBtnApmPesquisar.setText("Pesquisar");
        jBtnApmPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApmPesquisarActionPerformed(evt);
            }
        });

        jLblApmDataNascimento.setText("Data De Nascimento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPswApmSenha, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtApmNome))
                                .addGap(35, 35, 35))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblApmCpf)
                                    .addComponent(jLblApmId)
                                    .addComponent(jLblApmNome)
                                    .addComponent(jLblApmSenha)
                                    .addComponent(jFmtApmCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtApmId, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblApmApelido)
                            .addComponent(jTxtApmApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCboApmNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jChbApmAtivo))
                            .addComponent(jLblApmNivel)))
                    .addComponent(jLblApmDataNascimento)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jFmtApmDataNasc, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jBtnApmIncluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnApmAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnApmExcluir)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnApmCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnApmConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnApmPesquisar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblApmId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtApmId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblApmNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtApmNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLblApmCpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFmtApmCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLblApmSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPswApmSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblApmApelido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtApmApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(jLblApmNivel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCboApmNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jChbApmAtivo))))
                .addGap(18, 18, 18)
                .addComponent(jLblApmDataNascimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFmtApmDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnApmIncluir)
                    .addComponent(jBtnApmAlterar)
                    .addComponent(jBtnApmExcluir)
                    .addComponent(jBtnApmCancelar)
                    .addComponent(jBtnApmConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnApmPesquisar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPswApmSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPswApmSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPswApmSenhaActionPerformed

    private void jBtnApmIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApmIncluirActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jTxtApmId, jTxtApmNome, jTxtApmApelido, 
             jFmtApmCpf, jFmtApmDataNasc, jPswApmSenha,
             jCboApmNivel, jChbApmAtivo, jBtnApmConfirmar, jBtnApmCancelar);
        Util.habilitar(false, jBtnApmIncluir, jBtnApmAlterar, jBtnApmExcluir, jBtnApmPesquisar);
        Util.limpar(jTxtApmId, jTxtApmNome, jTxtApmApelido, 
                    jFmtApmCpf, jFmtApmDataNasc, jPswApmSenha,
                    jCboApmNivel, jChbApmAtivo);
    }//GEN-LAST:event_jBtnApmIncluirActionPerformed

    private void jBtnApmAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApmAlterarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jTxtApmId, jTxtApmNome, jTxtApmApelido, 
             jFmtApmCpf, jFmtApmDataNasc, jPswApmSenha,
             jCboApmNivel, jChbApmAtivo, jBtnApmConfirmar, jBtnApmCancelar);
        Util.habilitar(false, jBtnApmIncluir, jBtnApmAlterar, jBtnApmExcluir, jBtnApmPesquisar);
    }//GEN-LAST:event_jBtnApmAlterarActionPerformed

    private void jBtnApmExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApmExcluirActionPerformed
        // TODO add your handling code here:
        Util.pergunta("Deseja mesmo excluir?");
    }//GEN-LAST:event_jBtnApmExcluirActionPerformed

    private void jBtnApmCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApmCancelarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jTxtApmId, jTxtApmNome, jTxtApmApelido, 
             jFmtApmCpf, jFmtApmDataNasc, jPswApmSenha,
             jCboApmNivel, jChbApmAtivo, jBtnApmConfirmar, jBtnApmCancelar);
        Util.habilitar(true, jBtnApmIncluir, jBtnApmAlterar, jBtnApmExcluir, jBtnApmPesquisar);
    }//GEN-LAST:event_jBtnApmCancelarActionPerformed

    private void jBtnApmConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApmConfirmarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jTxtApmId, jTxtApmNome, jTxtApmApelido, 
             jFmtApmCpf, jFmtApmDataNasc, jPswApmSenha,
             jCboApmNivel, jChbApmAtivo, jBtnApmConfirmar, jBtnApmCancelar);
        Util.habilitar(true, jBtnApmIncluir, jBtnApmAlterar, jBtnApmExcluir, jBtnApmPesquisar);
        Util.limpar(jTxtApmId, jTxtApmNome, jTxtApmApelido, 
                    jFmtApmCpf, jFmtApmDataNasc, jPswApmSenha,
                    jCboApmNivel, jChbApmAtivo);
    }//GEN-LAST:event_jBtnApmConfirmarActionPerformed

    private void jBtnApmPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApmPesquisarActionPerformed
        // TODO add your handling code here:
        JDlgApmUsuarioPesquisar jDlgApmUsuarioPesquisar= new JDlgApmUsuarioPesquisar(null, true);
        jDlgApmUsuarioPesquisar.setVisible(true);
    }//GEN-LAST:event_jBtnApmPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgApmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgApmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgApmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgApmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgApmUsuario dialog = new JDlgApmUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnApmAlterar;
    private javax.swing.JButton jBtnApmCancelar;
    private javax.swing.JButton jBtnApmConfirmar;
    private javax.swing.JButton jBtnApmExcluir;
    private javax.swing.JButton jBtnApmIncluir;
    private javax.swing.JButton jBtnApmPesquisar;
    private javax.swing.JComboBox jCboApmNivel;
    private javax.swing.JCheckBox jChbApmAtivo;
    private javax.swing.JFormattedTextField jFmtApmCpf;
    private javax.swing.JFormattedTextField jFmtApmDataNasc;
    private javax.swing.JLabel jLblApmApelido;
    private javax.swing.JLabel jLblApmCpf;
    private javax.swing.JLabel jLblApmDataNascimento;
    private javax.swing.JLabel jLblApmId;
    private javax.swing.JLabel jLblApmNivel;
    private javax.swing.JLabel jLblApmNome;
    private javax.swing.JLabel jLblApmSenha;
    private javax.swing.JPasswordField jPswApmSenha;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTxtApmApelido;
    private javax.swing.JTextField jTxtApmId;
    private javax.swing.JTextField jTxtApmNome;
    // End of variables declaration//GEN-END:variables
}
