/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import tools.Util;

/**
 *
 * @author win10
 */
public class JDlgApmVendasProdutos extends javax.swing.JDialog {

    /**
     * Creates new form jDlgApmVendasProdutos
     */
    public JDlgApmVendasProdutos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Vendas Produto");
        setLocationRelativeTo(null);
        Util.habilitar(false, jTxtApmIdVendaProduto, jTxtApmIdVendas, jTxtApmIdProduto,
            jBtnApmConfirmar, jBtnApmCancelar);
        Util.limpar(jTxtApmIdVendaProduto, jTxtApmIdVendas, jTxtApmIdProduto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnApmIncluir = new javax.swing.JButton();
        jBtnApmAlterar = new javax.swing.JButton();
        jBtnApmConfirmar = new javax.swing.JButton();
        jBtnApmExcluir = new javax.swing.JButton();
        jLblApmIdVendasProdutos = new javax.swing.JLabel();
        jBtnApmCancelar = new javax.swing.JButton();
        jBtnApmPesquisar = new javax.swing.JButton();
        jLblApmIdProduto = new javax.swing.JLabel();
        jLblApmIdVendas = new javax.swing.JLabel();
        jTxtApmIdVendaProduto = new javax.swing.JTextField();
        jTxtApmIdProduto = new javax.swing.JTextField();
        jTxtApmIdVendas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtnApmIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnApmIncluir.setText("Incluir");
        jBtnApmIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApmIncluirActionPerformed(evt);
            }
        });

        jBtnApmAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnApmAlterar.setText("Alterar");
        jBtnApmAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApmAlterarActionPerformed(evt);
            }
        });

        jBtnApmConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.png"))); // NOI18N
        jBtnApmConfirmar.setText("Confirmar");
        jBtnApmConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApmConfirmarActionPerformed(evt);
            }
        });

        jBtnApmExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnApmExcluir.setText("Excluir");
        jBtnApmExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApmExcluirActionPerformed(evt);
            }
        });

        jLblApmIdVendasProdutos.setText("Id");

        jBtnApmCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnApmCancelar.setText("Cancelar");
        jBtnApmCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApmCancelarActionPerformed(evt);
            }
        });

        jBtnApmPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnApmPesquisar.setText("Pesquisar");
        jBtnApmPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApmPesquisarActionPerformed(evt);
            }
        });

        jLblApmIdProduto.setText("Id do Produto");

        jLblApmIdVendas.setText("Id das Vendas");

        jTxtApmIdVendaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtApmIdVendaProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jBtnApmIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnApmAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnApmExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnApmCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnApmConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnApmPesquisar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtApmIdVendas)
                    .addComponent(jTxtApmIdVendaProduto)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblApmIdVendasProdutos)
                            .addComponent(jLblApmIdProduto)
                            .addComponent(jLblApmIdVendas))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTxtApmIdProduto))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblApmIdVendasProdutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtApmIdVendaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLblApmIdProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtApmIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLblApmIdVendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtApmIdVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnApmIncluir)
                    .addComponent(jBtnApmAlterar)
                    .addComponent(jBtnApmExcluir)
                    .addComponent(jBtnApmCancelar)
                    .addComponent(jBtnApmConfirmar)
                    .addComponent(jBtnApmPesquisar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnApmIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApmIncluirActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jTxtApmIdVendaProduto, jTxtApmIdVendas, jTxtApmIdProduto,
            jBtnApmConfirmar, jBtnApmCancelar);
        Util.habilitar(false, jBtnApmIncluir, jBtnApmAlterar, jBtnApmExcluir, jBtnApmPesquisar);
        Util.limpar(jTxtApmIdVendaProduto, jTxtApmIdVendas, jTxtApmIdProduto);
    }//GEN-LAST:event_jBtnApmIncluirActionPerformed

    private void jBtnApmAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApmAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnApmAlterarActionPerformed

    private void jBtnApmConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApmConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnApmConfirmarActionPerformed

    private void jBtnApmExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApmExcluirActionPerformed
        // TODO add your handling code here:
        Util.pergunta("Deseja mesmo excluir?");
    }//GEN-LAST:event_jBtnApmExcluirActionPerformed

    private void jBtnApmCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApmCancelarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jTxtApmIdVendaProduto, jTxtApmIdVendas, jTxtApmIdProduto,
            jBtnApmConfirmar, jBtnApmCancelar);
        Util.habilitar(true, jBtnApmIncluir, jBtnApmAlterar, jBtnApmExcluir, jBtnApmPesquisar);
    }//GEN-LAST:event_jBtnApmCancelarActionPerformed

    private void jBtnApmPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApmPesquisarActionPerformed
        // TODO add your handling code here:jTxtId.setEnabled(true);
        Util.mensagem("Nao implementado");
    }//GEN-LAST:event_jBtnApmPesquisarActionPerformed

    private void jTxtApmIdVendaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtApmIdVendaProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtApmIdVendaProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgApmVendasProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgApmVendasProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgApmVendasProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgApmVendasProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgApmVendasProdutos dialog = new JDlgApmVendasProdutos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnApmAlterar;
    private javax.swing.JButton jBtnApmCancelar;
    private javax.swing.JButton jBtnApmConfirmar;
    private javax.swing.JButton jBtnApmExcluir;
    private javax.swing.JButton jBtnApmIncluir;
    private javax.swing.JButton jBtnApmPesquisar;
    private javax.swing.JLabel jLblApmIdProduto;
    private javax.swing.JLabel jLblApmIdVendas;
    private javax.swing.JLabel jLblApmIdVendasProdutos;
    private javax.swing.JTextField jTxtApmIdProduto;
    private javax.swing.JTextField jTxtApmIdVendaProduto;
    private javax.swing.JTextField jTxtApmIdVendas;
    // End of variables declaration//GEN-END:variables
}
