/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

/**
 *
 * @author win10
 */
public class JFmtApmMenu extends javax.swing.JFrame {

    /**
     * Creates new form JFrmApmMenu
     */
    public JFmtApmMenu() {
        initComponents();
        setTitle("Menu");
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemApmCliente = new javax.swing.JMenuItem();
        jMenuItemApmFuncionario = new javax.swing.JMenuItem();
        jMenuItemApmProduto = new javax.swing.JMenuItem();
        jMenuItemUsuario = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemApmSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemApmVendas = new javax.swing.JMenuItem();
        jMenuItemApmVendasProduto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Cadastro");

        jMenuItemApmCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        jMenuItemApmCliente.setText("Cliente");
        jMenuItemApmCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemApmClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemApmCliente);

        jMenuItemApmFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/grupo_1.png"))); // NOI18N
        jMenuItemApmFuncionario.setText("Funcionario");
        jMenuItemApmFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemApmFuncionarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemApmFuncionario);

        jMenuItemApmProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/produto.png"))); // NOI18N
        jMenuItemApmProduto.setText("Produto");
        jMenuItemApmProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemApmProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemApmProduto);

        jMenuItemUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        jMenuItemUsuario.setText("Usuario");
        jMenuItemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemUsuario);
        jMenu1.add(jSeparator1);

        jMenuItemApmSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        jMenuItemApmSair.setText("Sair");
        jMenuItemApmSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemApmSairActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemApmSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Movimento");

        jMenuItemApmVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/produto_1.png"))); // NOI18N
        jMenuItemApmVendas.setText("Vendas");
        jMenuItemApmVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemApmVendasActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemApmVendas);

        jMenuItemApmVendasProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/produto_1.png"))); // NOI18N
        jMenuItemApmVendasProduto.setText("Vendas produto");
        jMenuItemApmVendasProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemApmVendasProdutoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemApmVendasProduto);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemApmClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemApmClienteActionPerformed
        // TODO add your handling code here:
        JDlgApmCliente jDlgApmCliente = new JDlgApmCliente(null, true);
        jDlgApmCliente.setVisible(true);
    }//GEN-LAST:event_jMenuItemApmClienteActionPerformed

    private void jMenuItemApmFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemApmFuncionarioActionPerformed
        // TODO add your handling code here:
        JDlgApmFuncionario jDlgApmFuncionario = new JDlgApmFuncionario(null, true);
        jDlgApmFuncionario.setVisible(true);
    }//GEN-LAST:event_jMenuItemApmFuncionarioActionPerformed

    private void jMenuItemApmProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemApmProdutoActionPerformed
        // TODO add your handling code here:
        JDlgApmProduto jDlgApmProduto = new JDlgApmProduto(null, true);
        jDlgApmProduto.setVisible(true);
    }//GEN-LAST:event_jMenuItemApmProdutoActionPerformed

    private void jMenuItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioActionPerformed
        // TODO add your handling code here:
        JDlgApmUsuario jDlgApmUsuario = new JDlgApmUsuario(null, true);
        jDlgApmUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuItemUsuarioActionPerformed

    private void jMenuItemApmVendasProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemApmVendasProdutoActionPerformed
        // TODO add your handling code here:
        JDlgApmVendasProdutos jdApmVendasProdutos = new JDlgApmVendasProdutos(null, true);
        jdApmVendasProdutos.setVisible(true);
    }//GEN-LAST:event_jMenuItemApmVendasProdutoActionPerformed

    private void jMenuItemApmVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemApmVendasActionPerformed
        // TODO add your handling code here:
        JDlgApmVendas jdApmVendas = new JDlgApmVendas(null, true);
        jdApmVendas.setVisible(true);
    }//GEN-LAST:event_jMenuItemApmVendasActionPerformed

    private void jMenuItemApmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemApmSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItemApmSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFmtApmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFmtApmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFmtApmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFmtApmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFmtApmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemApmCliente;
    private javax.swing.JMenuItem jMenuItemApmFuncionario;
    private javax.swing.JMenuItem jMenuItemApmProduto;
    private javax.swing.JMenuItem jMenuItemApmSair;
    private javax.swing.JMenuItem jMenuItemApmVendas;
    private javax.swing.JMenuItem jMenuItemApmVendasProduto;
    private javax.swing.JMenuItem jMenuItemUsuario;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
