package bean;
// Generated 18/09/2025 15:44:13 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApmCliente generated by hbm2java
 */
@Entity
@Table(name="apm_cliente"
    ,catalog="sistema_athilio"
)
public class ApmCliente  implements java.io.Serializable {


     private int apmIdCliente;
     private String apmNome;
     private String apmApelido;
     private char apmSexo;
     private String apmCpf;
     private String apmRg;
     private Date apmDataNascimento;
     private String apmRua;
     private String apmBairro;
     private String apmCep;
     private String apmTelefone;
     private String apmCelular;
     private String apmEmail;
     private String apmAtivo;
     private String apmSenha;

    public ApmCliente() {
    }

	
    public ApmCliente(int apmIdCliente, String apmNome, String apmApelido, String apmCpf) {
        this.apmIdCliente = apmIdCliente;
        this.apmNome = apmNome;
        this.apmApelido = apmApelido;
        this.apmCpf = apmCpf;
    }
    public ApmCliente(int apmIdCliente, String apmNome, String apmApelido, char apmSexo, String apmCpf, String apmRg, Date apmDataNascimento, String apmRua, String apmBairro, String apmCep, String apmTelefone, String apmCelular, String apmEmail, String apmAtivo, String apmSenha) {
       this.apmIdCliente = apmIdCliente;
       this.apmNome = apmNome;
       this.apmApelido = apmApelido;
       this.apmSexo = apmSexo;
       this.apmCpf = apmCpf;
       this.apmRg = apmRg;
       this.apmDataNascimento = apmDataNascimento;
       this.apmRua = apmRua;
       this.apmBairro = apmBairro;
       this.apmCep = apmCep;
       this.apmTelefone = apmTelefone;
       this.apmCelular = apmCelular;
       this.apmEmail = apmEmail;
       this.apmAtivo = apmAtivo;
       this.apmSenha = apmSenha;
    }
   
     @Id 

    
    @Column(name="apm_idCliente", unique=true, nullable=false)
    public int getApmIdCliente() {
        return this.apmIdCliente;
    }
    
    public void setApmIdCliente(int apmIdCliente) {
        this.apmIdCliente = apmIdCliente;
    }

    
    @Column(name="apm_nome", nullable=false, length=50)
    public String getApmNome() {
        return this.apmNome;
    }
    
    public void setApmNome(String apmNome) {
        this.apmNome = apmNome;
    }

    
    @Column(name="apm_apelido", nullable=false, length=25)
    public String getApmApelido() {
        return this.apmApelido;
    }
    
    public void setApmApelido(String apmApelido) {
        this.apmApelido = apmApelido;
    }

    
    @Column(name="apm_sexo", length=10)
    public char getApmSexo() {
        return (char) this.apmSexo;
    }
    
    public void setApmSexo(char apmSexo) {
        this.apmSexo = apmSexo;
    }

    
    @Column(name="apm_cpf", nullable=false, length=14)
    public String getApmCpf() {
        return this.apmCpf;
    }
    
    public void setApmCpf(String apmCpf) {
        this.apmCpf = apmCpf;
    }

    
    @Column(name="apm_rg", length=10)
    public String getApmRg() {
        return this.apmRg;
    }
    
    public void setApmRg(String apmRg) {
        this.apmRg = apmRg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="apm_dataNascimento", length=10)
    public Date getApmDataNascimento() {
        return this.apmDataNascimento;
    }
    
    public void setApmDataNascimento(Date apmDataNascimento) {
        this.apmDataNascimento = apmDataNascimento;
    }

    
    @Column(name="apm_rua", length=50)
    public String getApmRua() {
        return this.apmRua;
    }
    
    public void setApmRua(String apmRua) {
        this.apmRua = apmRua;
    }

    
    @Column(name="apm_bairro", length=30)
    public String getApmBairro() {
        return this.apmBairro;
    }
    
    public void setApmBairro(String apmBairro) {
        this.apmBairro = apmBairro;
    }

    
    @Column(name="apm_cep", length=9)
    public String getApmCep() {
        return this.apmCep;
    }
    
    public void setApmCep(String apmCep) {
        this.apmCep = apmCep;
    }

    
    @Column(name="apm_telefone", length=55)
    public String getApmTelefone() {
        return this.apmTelefone;
    }
    
    public void setApmTelefone(String apmTelefone) {
        this.apmTelefone = apmTelefone;
    }

    
    @Column(name="apm_celular", length=11)
    public String getApmCelular() {
        return this.apmCelular;
    }
    
    public void setApmCelular(String apmCelular) {
        this.apmCelular = apmCelular;
    }

    
    @Column(name="apm_email", length=75)
    public String getApmEmail() {
        return this.apmEmail;
    }
    
    public void setApmEmail(String apmEmail) {
        this.apmEmail = apmEmail;
    }

    
    @Column(name="apm_ativo", length=1)
    public String getApmAtivo() {
        return this.apmAtivo;
    }
    
    public void setApmAtivo(String apmAtivo) {
        this.apmAtivo = apmAtivo;
    }

    
    @Column(name="apm_senha", length=20)
    public String getApmSenha() {
        return this.apmSenha;
    }
    
    public void setApmSenha(String apmSenha) {
        this.apmSenha = apmSenha;
    }

}


