package bean;
// Generated 18/09/2025 15:44:13 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApmProduto generated by hbm2java
 */
@Entity
@Table(name="apm_produto"
    ,catalog="sistema_athilio"
)
public class ApmProduto  implements java.io.Serializable {


     private int apmIdProduto;
     private String apmNome;
     private String apmMarca;
     private double apmValor;
     private String apmTamanho;
     private Date apmDataValidade;
     private String apmTipo;

    public ApmProduto() {
    }

	
    public ApmProduto(int apmIdProduto, String apmNome, String apmMarca, double apmValor, String apmTamanho, Date apmDataValidade, String apmTipo) {
        this.apmIdProduto = apmIdProduto;
        this.apmNome = apmNome;
        this.apmMarca = apmMarca;
        this.apmValor = apmValor;
        this.apmTamanho = apmTamanho;
        this.apmDataValidade = apmDataValidade;
        this.apmTipo = apmTipo;
    }
    public ApmProduto(int apmIdProduto, String apmNome, String apmMarca, double apmValor, String apmTamanho, Date apmDataValidade, String apmTipo, Set apmVendases) {
       this.apmIdProduto = apmIdProduto;
       this.apmNome = apmNome;
       this.apmMarca = apmMarca;
       this.apmValor = apmValor;
       this.apmTamanho = apmTamanho;
       this.apmDataValidade = apmDataValidade;
       this.apmTipo = apmTipo;

    }
   
     @Id 

    
    @Column(name="apm_idProduto", unique=true, nullable=false)
    public int getApmIdProduto() {
        return this.apmIdProduto;
    }
    
    public void setApmIdProduto(int apmIdProduto) {
        this.apmIdProduto = apmIdProduto;
    }

    
    @Column(name="apm_nome", nullable=false, length=40)
    public String getApmNome() {
        return this.apmNome;
    }
    
    public void setApmNome(String apmNome) {
        this.apmNome = apmNome;
    }

    
    @Column(name="apm_marca", nullable=false, length=35)
    public String getApmMarca() {
        return this.apmMarca;
    }
    
    public void setApmMarca(String apmMarca) {
        this.apmMarca = apmMarca;
    }

    
    @Column(name="apm_valor", nullable=false, precision=12, scale=0)
    public double getApmValor() {
        return this.apmValor;
    }
    
    public void setApmValor(double apmValor) {
        this.apmValor = apmValor;
    }

    
    @Column(name="apm_tamanho", nullable=false, length=15)
    public String getApmTamanho() {
        return this.apmTamanho;
    }
    
    public void setApmTamanho(String apmTamanho) {
        this.apmTamanho = apmTamanho;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="apm_dataValidade", nullable=false, length=10)
    public Date getApmDataValidade() {
        return this.apmDataValidade;
    }
    
    public void setApmDataValidade(Date apmDataValidade) {
        this.apmDataValidade = apmDataValidade;
    }

    
    @Column(name="apm_tipo", nullable=false, length=50)
    public String getApmTipo() {
        return this.apmTipo;
    }
    
    public void setApmTipo(String apmTipo) {
        this.apmTipo = apmTipo;
    }




}


