package bean;
// Generated 18/09/2025 15:44:13 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ApmUsuarios generated by hbm2java
 */
@Entity
@Table(name="apm_usuarios"
    ,catalog="sistema_athilio"
)
public class ApmUsuarios  implements java.io.Serializable {


     private int apmIdUsuario;
     private String apmNome;
     private String apmApelido;
     private String apmCpf;
     private String apmDataNascimento;
     private String apmSenha;
     private int apmNivel;
     private char apmAtivo;

    public ApmUsuarios() {
    }

    public ApmUsuarios(int apmIdUsuario, String apmNome, String apmApelido, String apmCpf, String apmDataNascimento, String apmSenha, int apmNivel, char apmAtivo) {
       this.apmIdUsuario = apmIdUsuario;
       this.apmNome = apmNome;
       this.apmApelido = apmApelido;
       this.apmCpf = apmCpf;
       this.apmDataNascimento = apmDataNascimento;
       this.apmSenha = apmSenha;
       this.apmNivel = apmNivel;
       this.apmAtivo = apmAtivo;
    }
   
     @Id 

    
    @Column(name="apm_idUsuario", unique=true, nullable=false)
    public int getApmIdUsuario() {
        return this.apmIdUsuario;
    }
    
    public void setApmIdUsuario(int apmIdUsuario) {
        this.apmIdUsuario = apmIdUsuario;
    }

    
    @Column(name="apm_nome", nullable=false, length=50)
    public String getApmNome() {
        return this.apmNome;
    }
    
    public void setApmNome(String apmNome) {
        this.apmNome = apmNome;
    }

    
    @Column(name="apm_apelido", nullable=false, length=25)
    public String getApmApelido() {
        return this.apmApelido;
    }
    
    public void setApmApelido(String apmApelido) {
        this.apmApelido = apmApelido;
    }

    
    @Column(name="apm_cpf", nullable=false, length=15)
    public String getApmCpf() {
        return this.apmCpf;
    }
    
    public void setApmCpf(String apmCpf) {
        this.apmCpf = apmCpf;
    }

    
    @Column(name="apm_dataNascimento", nullable=false, length=45)
    public String getApmDataNascimento() {
        return this.apmDataNascimento;
    }
    
    public void setApmDataNascimento(String apmDataNascimento) {
        this.apmDataNascimento = apmDataNascimento;
    }

    
    @Column(name="apm_senha", nullable=false, length=20)
    public String getApmSenha() {
        return this.apmSenha;
    }
    
    public void setApmSenha(String apmSenha) {
        this.apmSenha = apmSenha;
    }

    
    @Column(name="apm_nivel", nullable=false)
    public int getApmNivel() {
        return this.apmNivel;
    }
    
    public void setApmNivel(int apmNivel) {
        this.apmNivel = apmNivel;
    }

    
    @Column(name="apm_ativo", nullable=false, length=1)
    public char getApmAtivo() {
        return this.apmAtivo;
    }
    
    public void setApmAtivo(char apmAtivo) {
        this.apmAtivo = apmAtivo;
    }




}


