package bean;
// Generated 18/09/2025 15:44:13 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ApmVendasProduto generated by hbm2java
 */
@Entity
@Table(name="apm_vendas_produto"
    ,catalog="sistema_athilio"
)
public class ApmVendasProduto  implements java.io.Serializable {


     private int apmIdVendasProduto;
     private ApmProduto apmProduto;
     private ApmVendas apmVendas;

    public ApmVendasProduto() {
    }

    public ApmVendasProduto(int apmIdVendasProduto, ApmProduto apmProduto, ApmVendas apmVendas) {
       this.apmIdVendasProduto = apmIdVendasProduto;
       this.apmProduto = apmProduto;
       this.apmVendas = apmVendas;
    }
   
     @Id 

    
    @Column(name="apm_idVendas_produto", unique=true, nullable=false)
    public int getApmIdVendasProduto() {
        return this.apmIdVendasProduto;
    }
    
    public void setApmIdVendasProduto(int apmIdVendasProduto) {
        this.apmIdVendasProduto = apmIdVendasProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="apm_produtocol", nullable=false)
    public ApmProduto getApmProduto() {
        return this.apmProduto;
    }
    
    public void setApmProduto(ApmProduto apmProduto) {
        this.apmProduto = apmProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="apm_vendas", nullable=false)
    public ApmVendas getApmVendas() {
        return this.apmVendas;
    }
    
    public void setApmVendas(ApmVendas apmVendas) {
        this.apmVendas = apmVendas;
    }




}


