package bean;
// Generated 18/09/2025 15:44:13 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ApmVendas generated by hbm2java
 */
@Entity
@Table(name="apm_vendas"
    ,catalog="sistema_athilio"
)
public class ApmVendas  implements java.io.Serializable {


     private int apmIdVendas;
     private int apmCliente;
     private int apmProduto;

    public ApmVendas() {
    }

	
    public ApmVendas(int apmIdVendas, int apmCliente, int apmProduto) {
        this.apmIdVendas = apmIdVendas;
        this.apmCliente = apmCliente;
        this.apmProduto = apmProduto;
    }
    public ApmVendas(int apmIdVendas, int apmCliente, int apmProduto, Set apmVendasProdutos) {
       this.apmIdVendas = apmIdVendas;
       this.apmCliente = apmCliente;
       this.apmProduto = apmProduto;
    }
   
     @Id 

    
    @Column(name="apm_idVendas", unique=true, nullable=false)
    public int getApmIdVendas() {
        return this.apmIdVendas;
    }
    
    public void setApmIdVendas(int apmIdVendas) {
        this.apmIdVendas = apmIdVendas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="apm_idCliente", nullable=false)
    public int getApmCliente() {
        return this.apmCliente;
    }
    
    public void setApmCliente(int apmCliente) {
        this.apmCliente = apmCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="apm_idProduto", nullable=false)
    public int getApmProduto() {
        return this.apmProduto;
    }
    
    public void setApmProduto(int apmProduto) {
        this.apmProduto = apmProduto;
    }

}


